In [ ]:
from google.colab import files
x = files.upload()

Saving Maternal_Health_Risk_Data_Set.csv to Maternal_Health_Risk_Data_Set.csv


In [ ]:
import pandas as pd
data = pd.read_csv('Maternal_Health_Risk_Data_Set.csv', delimiter = ',')
data.head()
# Binary classification is done in phrase 1

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  in-Risk
0   25         130           80  15.0      98.0         86        1
1   35         140           90  13.0      98.0         70        1
2   29          90           70   8.0     100.0         80        1
3   30         140           85   7.0      98.0         70        1
4   35         120           60   6.1      98.0         76        0

In [ ]:
import numpy as np
dataset = np.genfromtxt('Maternal_Health_Risk_Data_Set.csv',delimiter=',', skip_header = True)
np.set_printoptions(formatter = {'float': '{:0.2f}'.format})
print(dataset.shape)

(1014, 7)


In [ ]:
print(dataset[:5, :]) # with fixed decimal place and skipped header

[[25.00 130.00 80.00 15.00 98.00 86.00 1.00]
 [35.00 140.00 90.00 13.00 98.00 70.00 1.00]
 [29.00 90.00 70.00 8.00 100.00 80.00 1.00]
 [30.00 140.00 85.00 7.00 98.00 70.00 1.00]
 [35.00 120.00 60.00 6.10 98.00 76.00 0.00]]


In [ ]:
X=dataset[:, :-1] 
Y=dataset[:,-1]
# separate input and output columns

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(1, input_dim=len(X[0,:]), activation='sigmoid'))

In [ ]:
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics='accuracy' )

In [ ]:
model.fit(x= X, y=Y, epochs = 256, verbose = 1)

Epoch 1/256
32/32 [==============================] - 0s 1ms/step - loss: 0.5621 - accuracy: 0.6538
Epoch 2/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5615 - accuracy: 0.6716
Epoch 3/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5565 - accuracy: 0.6677
Epoch 4/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5567 - accuracy: 0.6686
Epoch 5/256
32/32 [==============================] - 0s 1ms/step - loss: 0.5571 - accuracy: 0.6736
Epoch 6/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5551 - accuracy: 0.6686
Epoch 7/256
32/32 [==============================] - 0s 1ms/step - loss: 0.5610 - accuracy: 0.6627
Epoch 8/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5560 - accuracy: 0.6647
Epoch 9/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5584 - accuracy: 0.6726
Epoch 10/256
32/32 [==============================] - 0s 2ms/step - loss: 0.5549 - accuracy: 0.6647
Epoch 11/

In [ ]:
print(Y[:10])

[1.00 1.00 1.00 1.00 0.00 1.00 1.00 1.00 1.00 1.00]


In [ ]:
predictions = model.predict(X)
print(predictions[:10].T)

[[0.99 0.95 0.26 0.52 0.40 0.59 0.61 0.63 0.26 1.00]]


In [ ]:
# as we can see here, this model makes mistakes and the single layer model's
# accuracy is not increasing no matter how many epochs repeated. So, now let's
# do it within multiple layers

In [ ]:
mean = X.mean(axis = 0)
X -= mean
range = X.max(axis = 0) - X.min(axis = 0)
X /= range
# mean normalization just like in phrase 1

In [ ]:
model2= Sequential()
model2.add(Dense(16, input_dim= len(X[0,:]), activation = 'relu' ))
model2.add(Dense(8, activation = 'relu' ))
model2.add(Dense(4, activation = 'relu' ))
model2.add(Dense(1, activation = 'sigmoid')) 


In [ ]:
model2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 16)                112       
                                                                 
 dense_19 (Dense)            (None, 8)                 136       
                                                                 
 dense_20 (Dense)            (None, 4)                 36        
                                                                 
 dense_21 (Dense)            (None, 1)                 5         
                                                                 
Total params: 289
Trainable params: 289
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model2.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics='accuracy' )
# build for multi-layered model

In [ ]:
model2.fit(x= X, y=Y, epochs = 2560, verbose = 1) # 4 times

Streaming output truncated to the last 5000 lines.
32/32 [==============================] - 0s 2ms/step - loss: 0.2077 - accuracy: 0.9112
Epoch 62/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2169 - accuracy: 0.9053
Epoch 63/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2053 - accuracy: 0.9073
Epoch 64/2560
32/32 [==============================] - 0s 3ms/step - loss: 0.2170 - accuracy: 0.8994
Epoch 65/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2102 - accuracy: 0.9063
Epoch 66/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2032 - accuracy: 0.8945
Epoch 67/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2063 - accuracy: 0.9083
Epoch 68/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2128 - accuracy: 0.9034
Epoch 69/2560
32/32 [==============================] - 0s 2ms/step - loss: 0.2081 - accuracy: 0.9083
Epoch 70/2560
32/32 [==============================] -

In [ ]:
print(Y[:10])

[1.00 1.00 1.00 1.00 0.00 1.00 1.00 1.00 1.00 1.00]


In [ ]:
predictions2 = model2.predict(X)
print(predictions2[:10].T)

[[1.00 1.00 1.00 1.00 0.48 1.00 1.00 1.00 0.43 1.00]]


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [ ]:
my_accuracy= accuracy_score(Y, predictions2.round())

In [ ]:
print(my_accuracy)

0.9161735700197239


In [ ]:
print(Y.sum()/len(Y)) # about 60% are positive

0.5996055226824457


In [66]:
%%shell
jupyter nbconvert --to html /content/Project_Phrase_2.ipynb

[NbConvertApp] Converting notebook /content/Project_Phrase_2.ipynb to html
[NbConvertApp] Writing 593739 bytes to /content/Project_Phrase_2.html
